name: Push

on:
  push:
  workflow_dispatch:

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.WORDPRESS_SFTP_HOST }}
          server-dir: /htdocs/${{ secrets.WORDPRESS_PAGE }}/
          username: ${{ secrets.WORDPRESS_SFTP_USERNAME }}
          password: ${{ secrets.WORDPRESS_SFTP_PASSWORD }}
