name: Push

on:
  push:
  workflow_dispatch:

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build && ls -l build
      - name: Populate .git-ftp-include
        run: |
          touch .git-ftp-include
          find build -type f | while read file; do printf '!%s\n' "$file" >> .git-ftp-include; done
      - name: Push
        uses: Automattic/FTP-Deploy-Action@3.0.1
        with:
          local-dir: build
          ftp-server: sftp://sftp.wp.com/htdocs/${{ secrets.WORDPRESS_PAGE }}
          ftp-username: ${{ secrets.WORDPRESS_SFTP_USERNAME }}
          ftp-password: ${{ secrets.WORDPRESS_SFTP_PASSWORD }}
          known-hosts: "sftp.wp.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB\
                    AAABAQDwfT/YEhOKO2Z0+XrjRqUS5Q2Ali6AlhOhZtzlIfMOvm03Sype\
                    DJH70tlUHasS+nm0SnZ01fOiEeAXa91ZhMihIYUT3nTGuiA2J3uVYsyS\
                    CJefvhWc0kg1FbEus3V3cVmx4e3XctdkzLbOgPNngypZocbP+8yCpbx6\
                    Kb9lihmgTjgGn2QzbK1enRSzsN/CbjVhej9jwukbrWqdCrQsKAsoZ2p6\
                    YCtcKbHS+Yy4RwcO9PxZUBkeMXUrejms027bRcdVfwf55hWSD9xYEHpE\
                    HupkSL4ofWs3UKeRGz+jCCzl7Nu0S6VSwK4Zzll0auHI0Hwh8WKTJbSn\
                    1gxCdF93/rmP"
