name: Push

on:
  push:
  workflow_dispatch:

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: /htdocs/${{ secrets.WORDPRESS_PAGE }}
          host: ${{ secrets.WORDPRESS_SFTP_HOST }}
          username: ${{ secrets.WORDPRESS_SFTP_USERNAME }}
          password: ${{ secrets.WORDPRESS_SFTP_PASSWORD }}
          rmRemote: true
