name: Push

on:
  push:
  workflow_dispatch:

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Push
        run: |
          sshpass -p "${{ secrets.WORDPRESS_SFTP_PASSWORD }}" scp -r * ${{ secrets.WORDPRESS_SFTP_HOST }}:${{ secrets.WORDPRESS_SFTP_PORT }}/htdocs/${{ secrets.WORDPRESS_PAGE }}